// Menu data for the assistant. Keep in sync with src/data/products.ts.
export const MENU = [
  ["Dosa","breakfast",80,"veg","mild","Crispy crepe of fermented rice and lentil batter"],
  ["Masala Dosa","breakfast",100,"veg","medium","Dosa filled with spiced potato"],
  ["Idli","breakfast",60,"veg","mild","Soft steamed rice cakes with sambar and chutney"],
  ["Medu Vada","breakfast",70,"veg","mild","Crispy lentil donuts"],
  ["Uttapam","breakfast",90,"veg","mild","Thick pancake topped with vegetables"],
  ["Appam","breakfast",85,"veg","mild","Fluffy lace-edged pancakes with stew"],
  ["Puttu","breakfast",75,"veg","mild","Steamed rice cake with coconut"],
  ["Upma","breakfast",65,"veg","mild","Savory semolina with vegetables"],
  ["Pongal","breakfast",70,"veg","mild","Rice and lentils with black pepper and ghee"],
  ["Hyderabadi Biryani","biryani",280,"non-veg","hot","Dum-cooked basmati with marinated meat"],
  ["Kolkata Biryani","biryani",260,"non-veg","medium","Fragrant biryani with potato and egg"],
  ["Thalassery Biryani","biryani",290,"non-veg","hot","Malabar biryani with short-grain rice"],
  ["Andhra Biryani","biryani",270,"non-veg","hot","Fiery Andhra-style biryani"],
  ["Chettinad Biryani","biryani",275,"non-veg","hot","Tamil Nadu biryani with Chettinad spices"],
  ["Dindigul Biryani","biryani",265,"non-veg","hot","Seeraga samba rice with special masala"],
  ["Ambur Biryani","biryani",270,"non-veg","medium","Tamil Nadu style with seeraga samba rice"],
  ["Mangalore Biryani","biryani",275,"non-veg","medium","Coastal Karnataka biryani"],
  ["Donne Biryani","biryani",260,"non-veg","hot","Bangalore biryani served in a leaf bowl"],
  ["Beary Biryani","biryani",280,"non-veg","hot","Mangalorean Beary community biryani"],
  ["Pakki Biryani","biryani",270,"non-veg","medium","Meat and rice cooked separately then layered"],
  ["Chettinad Chicken Curry","main-course",240,"non-veg","hot","Spicy chicken in Chettinad masala"],
  ["Fish Molee","main-course",260,"non-veg","mild","Kerala fish curry in coconut milk"],
  ["Kerala Prawn Curry","main-course",320,"non-veg","hot","Tangy spicy prawns with coconut"],
  ["Kori Gassi","main-course",250,"non-veg","hot","Mangalorean chicken curry"],
  ["Avial","main-course",180,"veg","mild","Mixed vegetables in coconut-yogurt gravy"],
  ["Sambar","main-course",120,"veg","medium","Lentil and vegetable stew"],
  ["Rasam","main-course",100,"veg","medium","Tangy tamarind pepper soup"],
  ["Meen Pollichathu","main-course",280,"non-veg","hot","Fish roasted in banana leaf"],
  ["Chicken 65","appetizer",220,"non-veg","hot","Spicy deep-fried chicken"],
  ["Sundal","appetizer",80,"veg","mild","Seasoned chickpea snack"],
  ["Malabar Parotta","appetizer",50,"veg","mild","Flaky layered flatbread"],
  ["Lemon Rice","rice",110,"veg","mild","Tangy lemon rice with tempering"],
  ["Tamarind Rice (Puliyogare)","rice",120,"veg","medium","Tangy tamarind rice"],
  ["Bisi Bele Bath","rice",140,"veg","medium","Karnataka rice with lentils and vegetables"],
  ["Payasam","dessert",90,"veg","-","Sweet milk pudding"],
  ["Mysore Pak","dessert",100,"veg","-","Gram flour and ghee sweet"],
  ["Kozhukatta","dessert",85,"veg","-","Steamed rice dumplings with sweet filling"],
] as const;

export const menuText = () =>
  MENU.map(([n, c, p, v, s, d]) => `- ${n} | ${c} | ₹${p} | ${v} | spice: ${s} | ${d}`).join("\n");
